### ISSUE TITLE
Missing R code

### ISSUE THREAD

**Issue by PabloMosUU** [GU-CLASP/semantic-shift-in-social-networks#1]
Dear Bill,

In your paper, you say that R code would be posted online upon publication. However, it is still not there. Could you share it, please?

Best,

Pablo

**Comment by winobes** [comment]
Dear Pablo,

Thank you for letting us know. The R code is now uploaded (in a jupyter notebook) [here](https://github.com/GU-CLASP/semantic-shift-in-social-networks/blob/main/change-clustering-MarData.ipynb).

Best,
Bill

**Comment by PabloMosUU** [comment]
Great, thanks

Pablo Mosteiro | Assistant Professor | Utrecht University | Methodology and Statistics | Sjoerd Groenmangebouw, Padualaan 14, 3584 CH Utrecht | room C1.22 | ***@***.******@***.***> | www.uu.nl/staff/PJMosteiroRomero<http://www.uu.nl/staff/PJMosteiroRomero> | Present on Mo-Thu

From: Bill Noble ***@***.***>
Date: Tuesday, 12 March 2024 at 18:22
To: GU-CLASP/semantic-shift-in-social-networks ***@***.***>
Cc: Mosteiro Romero, P.J. (Pablo) ***@***.***>, Author ***@***.***>
Subject: Re: [GU-CLASP/semantic-shift-in-social-networks] Missing R code (Issue #1)
CAUTION: This email originated from outside of Utrecht University. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Dear Pablo,

Thank you for letting us know. The R code is now uploaded (in a jupyter notebook) here<https://github.com/GU-CLASP/semantic-shift-in-social-networks/blob/main/change-clustering-MarData.ipynb>.

Best,
Bill
